services:
  hiss:
    image: ghcr.io/distantgeek/home-improvement-search-system:latest
    container_name: hiss
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: YOUR_NPM_NETWORK_NAME   # replace with output of: docker network ls
